{
 "title": "Kubernetes / Capacity Planning / Requests",
 "description": "Provides information relevant to fine-tuning container resource requests in Kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\"}, pod_name)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Over-requested CPU",
   "type": "graph",
   "description": "Shows a difference between requested CPU and used CPU time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "  sum(\n    container_spec_cpu_shares{name=~'.+',container_name!='POD', node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"})\n  by (namespace, container_name)/1024\n  -\n  sum(\n    rate(\n      container_cpu_usage_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m]\n    )\n  ) by (namespace, container_name)",
     "legendFormat": "{{ namespace }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "Requestable memory",
   "type": "graph",
   "description": "Shows allocatable memory - memory requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_allocatable_memory_bytes{node=~\"$node\"}\n) by (node)/(1024^3) - sum(\n  kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}\n) by (node)/(1024^3)",
     "legendFormat": "Requestable memory ({{ node }})"
    }
   ]
  },
  {
   "title": "Over-requested CPU (cores)",
   "type": "table",
   "description": "Shows a difference between requested CPU and used CPU time by the containers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sort_desc(\n  sum(\n    container_spec_cpu_shares{name=~'.+',container_name!='POD', node=~\"$node\", namespace=~\"$namespace\", container_name=~\"$container\"})\n  by (namespace, container_name)/1024\n  -\n  sum(\n    rate(\n      container_cpu_usage_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\", container_name=~\"$container\"}[5m]\n    )\n  ) by (namespace, container_name)\n)",
     "legendFormat": "{{ namespace }}/{{ container_name }}"
    }
   ]
  }
 ]
}